### ISSUE TITLE
블로그 글에서 다른 사이트로 이동할 수 있는 링크 UI 향상해보기

### ISSUE THREAD

**Issue by jaem1n207** [jaem1n207/lazy-dev#74]
## 설명

블로그에서 강조하려는 텍스트에 밑줄을 추가하여 하이라이트하는 스타일을 추가하고 싶었습니다. 그러나 밑줄을 주게 되면 a 태그의 기본 스타일과 겹쳐 사용자가 링크인지, 강조된 텍스트인지 헷갈릴 수 있습니다. 이에 링크를 확실하게 표현하기 위해 적용한 UI를 설명하는 문서입니다.

## 영감

Inpa님의 블로그 글을 읽다 다른 사이트로 이동하는 링크에 아래처럼 브라우저 로고를 표시해둔 것을 보았고 이에 영감을 얻었습니다.

![image](https://github.com/jaem1n207/lazy-dev/assets/50766847/e0f38894-5912-4e96-9f09-8f84dae0ada8)

여기에 더해 고정적으로 Chrome 로고를 보여주는 게 아니라 사용자의 브라우저를 감지해 Firefox, Edge, Safari 등의 로고를 표시할 수 있게끔 구현하기  시작했습니다.

## 사용자의 브라우저 식별

`navigator.userAgentData` 속성을 사용해 브라우저를 식별할 수 있습니다.

```ts
// index.d.ts
declare global {
  interface UserAgentData {
    brands: Array<{
      brand: string;
      version: string;
    }>;
    mobile: boolean;
    platform: string;
  }

  interface NavigatorID {
    userAgentData: UserAgentData;
  }
}

// gatsby-node.ts
const isNavigatorDefined = typeof navigator !== "undefined";
const userAgent = isNavigatorDefined
  ? navigator.userAgentData && Array.isArray(navigator.userAgentData.brands)
    ? navigator.userAgentData.brands
        .map((brand) => `${brand.brand.toLowerCase()} ${brand.version}`)
        .join(" ")
    : navigator.userAgent.toLowerCase()
  : "some useragent";

const isChromium = userAgent.includes("chrome") || userAgent.includes("chromium");
const isFirefox =
  userAgent.includes("firefox") ||
  userAgent.includes("thunderbird") ||
  userAgent.includes("librewolf");
const isOpera = isChromium && (userAgent.includes("opr") || userAgent.includes("opera"));
const isEdge = isChromium && userAgent.includes("edg");
const isChrome = isChromium && !isOpera && !isEdge;
const isSafari = !isChromium && userAgent.includes("safari");

const brand = Object.keys(brandMap).find((key) => brandMap[key]);

document.documentElement.classList.add(`brand-${brand || "chromium"}`);
```

위 코드에서 사용자의 브라우저를 식별한 뒤 `document.documentElement` 요소에 `brand-${사용자 브라우저}` 클래스를 추가했습니다:

![image](https://github.com/jaem1n207/lazy-dev/assets/50766847/611481fd-c897-4175-979a-d568babd7e73)

그리고 각 브라우저 로고 `svg` 파일들을 준비하고 클래스 속성의 값을 기반으로 알맞은 로고 svg 경로를 설정해줍니다:

```css
html.brand-chrome a::before,
html.brand-firefox a::before,
html.brand-safari a::before,
html.brand-edge a::before,
html.brand-opera a::before {
  content: "";
  display: inline-block;
  width: 14px;
  height: 14px;
  margin-right: 2px;
  vertical-align: middle;
  background-size: contain;
  background-repeat: no-repeat;
}
html.brand-chrome a::before {
  background-image: url("/assets/icons/chrome-logo.svg");
}
html.brand-firefox a::before {
  background-image: url("/assets/icons/firefox-logo.svg");
}
html.brand-safari a::before {
  background-image: url("/assets/icons/safari-logo.svg");
}
html.brand-edge a::before {
  background-image: url("/assets/icons/edge-logo.svg");
}
html.brand-opera a::before {
  background-image: url("/assets/icons/opera-logo.svg");
}
```

이제 사용자의 브라우저를 감지해 링크 앞에 로고를 표시합니다. 간단하게 3개의 브라우저에서 잘 동작하는지 확인해보겠습니다:

- Chrome
- ![image](https://github.com/jaem1n207/lazy-dev/assets/50766847/17fb0207-582c-450e-aa1b-48d0be68787e)
- Safari
- ![image](https://github.com/jaem1n207/lazy-dev/assets/50766847/cf99eec4-b45a-49a6-9d69-b5e3a06dd631)
- Opera
- <img width="186" alt="image" src="https://github.com/jaem1n207/lazy-dev/assets/50766847/2532eb91-d1d4-4a67-9e41-14768812cb50">

이제 강조된 텍스트와 다른 사이트로 이동하는 링크를 헷갈리지 않게 되었습니다.
